# Generated by Django 2.0.2 on 2020-05-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ece', '0002_auto_20200523_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedIn',
            field=models.URLField(blank=True, null=True),
        ),
    ]
