# Generated by Django 2.0.2 on 2020-05-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ece', '0004_auto_20200523_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('notice_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
