# Generated by Django 2.0.2 on 2020-05-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ece', '0005_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_date',
            field=models.DateField(null=True),
        ),
    ]
