# Generated by Django 2.0.2 on 2020-05-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ece', '0006_auto_20200523_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
